### ISSUE TITLE
Menu button doesn't close smoothly

### ISSUE THREAD

**Issue by rubaghekyan** [PatriotOrg/HighHopes#1]
https://github.com/PatriotOrg/HighHopes/assets/153749223/8233be16-fa69-4c6d-8668-4b766294b1c0

After installation exe appears popup "Web AD Blocker (IPC-A)" where the menu button doesn't close smoothly

**Comment by radiolondra** [comment]
This is an HTML page created just to show included features. Also, the menu button follows the bootstrap's NAV, so you could ask to Bootstrap why this happens.
