### ISSUE TITLE
Cancel and X buttons don't clickable.

### ISSUE THREAD

**Issue by rubaghekyan** [PatriotOrg/HighHopes#2]
https://github.com/PatriotOrg/HighHopes/assets/153749223/b0ca3123-cdff-48de-ba5b-23a6c56296c1

During installation, the "Cancel" and "X" buttons don't clickable.

You can see the video here.

**Comment by radiolondra** [comment]
Iknow, while installing the process cannot be interrupted, so the Cancel button and X are disabled. It is normal for complex installations.
